
library(Rsamtools)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(GenomicFeatures)
library(GenomicAlignments)
library(BiocParallel)
library(edgeR)
library(limma)
library(Glimma)
library(gplots)
library(RColorBrewer)
library(org.Hs.eg.db)
